SiteMonitoring/Models/Site.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SiteMonitoring.Models
{
    public class Site
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public bool IsAvailable { get; set; }
    }
}

SiteMonitoring/Controllers/SitesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SiteMonitoring.Models;

namespace SiteMonitoring.Controllers
{
    public class SitesController : Controller
    {
        private readonly SiteMonitoringContext _context;

        public SitesController(SiteMonitoringContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Sites.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Sites
                .SingleOrDefaultAsync(m => m.Id == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Url")] Site site)
        {
            if (ModelState.IsValid)
            {
                _context.Add(site);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(site);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var site = await _context.Sites.SingleOrDefaultAsync(m => m.Id == id);
            if (site == null)
            {
                return NotFound();
            }
            return View(site);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Url")] Site site)
        {
            if (id != site.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(site);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SiteExists(site.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(site);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var site = await _context.Sites
                .SingleOrDefaultAsync(m => m.Id == id);
            if (site == null)
            {
                return NotFound();
            }

            return View(site);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var site = await _context.Sites.SingleOrDefaultAsync(m => m.Id == id);
            _context.Sites.Remove(site);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SiteExists(int id)
        {
            return _context.Sites.Any(e => e.Id == id);
        }
    }
}

SiteMonitoring/Views/Sites/Create.cshtml
@model SiteMonitoring.Models.Site
@{
    ViewBag.Title = "Добавление сайта";
}

<ol class="breadcrumb">
    <li><a asp-action="Index" asp-controller="Home">Главная</a></li>
    <li><a asp-action="Index" asp-controller="Sites">Сайты</a></li>
    <li class="active">@ViewBag.Title</li>
</ol>
<div class="container-fluid">
    <form asp-action="Create">
        <div class="panel panel-primary">
            <div class="panel-heading">@ViewBag.Title</div>
            <div class="panel-body">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Url" class="control-label"></label>
                    <input asp-for="Url" class="form-control" />
                    <span asp-validation-for="Url" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Создать" class="btn btn-primary btn-block" />
        </div>
        <a asp-action="Index" asp-controller="Sites" class="btn btn-default btn-block" role="button">Назад</a>
    </form>
</div>

SiteMonitoring/Views/Sites/Delete.cshtml
@model SiteMonitoring.Models.Site
@{
    ViewBag.Title = "Удаление сайта";
}

<div class="container-fluid">
    <div class="panel panel-primary">
        <div class="panel-heading">@ViewBag.Title</div>
        <table class="table">
            <tbody>
                <tr>
                    <th scope="row">Название</th>
                    <td>@Model.Url</td>
                </tr>
            </tbody>
        </table>
    </div>
    <form asp-action="Delete" method="post">
        <div class="form-group">
            <input type="submit" class="btn btn-primary btn-block" value="Удалить" />
        </div>
        <a asp-action="Index" asp-controller="Sites" class="btn btn-default btn-block" role="button">Назад</a>
    </form>
</div>

SiteMonitoring/Views/Sites/Details.cshtml
@model SiteMonitoring.Models.Site
@{
    ViewBag.Title = "Подробная информация";
}

<ol class="breadcrumb">
    <li><a asp-action="Index" asp-controller="Home">Главная</a></li>
    <li><a asp-action="Index" asp-controller="Sites">Сайты</a></li>
    <li class="active">@ViewBag.Title</li>
</ol>
<div class="container-fluid">
    <div class="panel panel-primary">
        <div class="panel-heading">@ViewBag.Title</div>
        <table class="table">
            <tbody>
                <tr>
                    <th scope="row">Название</th>
                    <td>@Model.Url</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="form-group">
        <a asp-action="Edit" class="btn btn-primary btn-block" asp-route-id="@Model.Id">Изменить</a>
    </div>
    <a asp-action="Index" asp-controller="Sites" class="btn btn-default btn-block" role="button">Назад</a>
</div>

SiteMonitoring/Views/Sites/Edit.cshtml
@model SiteMonitoring.Models.Site
@{
    ViewBag.Title = "Изменение сайта";
}

<ol class="breadcrumb">
    <li><a asp-action="Index" asp-controller="Home">Главная</a></li>
    <li><a asp-action="Index" asp-controller="Sites">Сайты</a></li>
    <li class="active">@ViewBag.Title</li>
</ol>
<div class="container-fluid">
    <form asp-action="Edit">
        <div class="panel panel-primary">
            <div class="panel-heading">@ViewBag.Title</div>
            <div class="panel-body">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Url" class="control-label"></label>
                    <input asp-for="Url" class="form-control" />
                    <span asp-validation-for="Url" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Изменить" class="btn btn-primary btn-block" />
        </div>
        <a asp-action="Index" asp-controller="Sites" class="btn btn-default btn-block" role="button">Назад</a>
    </form>
</div>

SiteMonitoring/Views/Sites/Index.cshtml
@model IEnumerable<SiteMonitoring.Models.Site>
@{
    ViewBag.Title = "Sites";
}

<ol class="breadcrumb">
    <li><a asp-action="Index" asp-controller="Home">Главная</a></li>
    <li class="active">@ViewBag.Title</li>
</ol>

<div class="container-fluid">
    <div class="panel panel-primary">
        <div class="panel-heading">@ViewBag.Title</div>
        <table class="table">
            <tr>
                <th>Сайты</th>
                <th>Действия</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Url)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id"><span class="glyphicon glyphicon-pencil"></span></a> |
                        <a asp-action="Details" asp-route-id="@item.Id"><span class="glyphicon glyphicon-info-sign"></span></a> |
                        <a asp-action="Delete" asp-route-id="@item.Id"><span class="glyphicon glyphicon-trash"></span></a>
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="form-group">
        <a class="btn btn-primary btn-block" asp-controller="Sites" asp-action="Create" role="button">Добавить</a>
    </div>
</div>