SiteMonitoring/Models/TimeSpan.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SiteMonitoring.Models
{
    public class TimeSpan
    {
        public int Id { get; set; } 
        public int Minutes { get; set; }
    }
}

SiteMonitoring/Controllers/TimeSpanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SiteMonitoring.Models;

namespace SiteMonitoring.Controllers
{
    public class TimeSpanController : Controller
    {
        private readonly SiteMonitoringContext _context;

        public TimeSpanController(SiteMonitoringContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.TimeSpan.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var time = await _context.TimeSpan
                .SingleOrDefaultAsync(m => m.Id == id);
            if (time == null)
            {
                return NotFound();
            }

            return View(time);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Minutes")] Site site)
        {
            if (ModelState.IsValid)
            {
                _context.Add(site);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(site);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var site = await _context.TimeSpan.SingleOrDefaultAsync(m => m.Id == id);
            if (site == null)
            {
                return NotFound();
            }
            return View(site);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Minutes")] Site site)
        {
            if (id != site.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(site);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SiteExists(site.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(site);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var site = await _context.TimeSpan
                .SingleOrDefaultAsync(m => m.Id == id);
            if (site == null)
            {
                return NotFound();
            }

            return View(site);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var site = await _context.TimeSpan.SingleOrDefaultAsync(m => m.Id == id);
            _context.TimeSpan.Remove(site);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SiteExists(int id)
        {
            return _context.TimeSpan.Any(e => e.Id == id);
        }
    }
}

SiteMonitoring/Views/TimeSpan/Create.cshtml
@model SiteMonitoring.Models.TimeSpan
@{
    ViewBag.Title = "Добавление промежутка времени";
}

<ol class="breadcrumb">
    <li><a asp-action="Index" asp-controller="Home">Главная</a></li>
    <li><a asp-action="Index" asp-controller="TimeSpan">Промежуток времени</a></li>
    <li class="active">@ViewBag.Title</li>
</ol>
<div class="container-fluid">
    <form asp-action="Create">
        <div class="panel panel-primary">
            <div class="panel-heading">@ViewBag.Title</div>
            <div class="panel-body">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Minutes" class="control-label"></label>
                    <input asp-for="Minutes" class="form-control" />
                    <span asp-validation-for="Minutes" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Создать" class="btn btn-primary btn-block" />
        </div>
        <a asp-action="Index" asp-controller="TimeSpan" class="btn btn-default btn-block" role="button">Назад</a>
    </form>
</div>

SiteMonitoring/Views/TimeSpan/Delete.cshtml
@model SiteMonitoring.Models.TimeSpan
@{
    ViewBag.Title = "Удаление промежутка времени";
}
<ol class="breadcrumb">
    <li><a asp-action="Index" asp-controller="Home">Главная</a></li>
    <li><a asp-action="Index" asp-controller="TimeSpan">Промежуток времени</a></li>
    <li class="active">@ViewBag.Title</li>
</ol>
<div class="container-fluid">
    <div class="panel panel-primary">
        <div class="panel-heading">@ViewBag.Title</div>
        <table class="table">
            <tbody>
                <tr>
                    <th scope="row">Название</th>
                    <td>@Model.Minutes</td>
                </tr>
            </tbody>
        </table>
    </div>
    <form asp-action="Delete" method="post">
        <div class="form-group">
            <input type="submit" class="btn btn-primary btn-block" value="Удалить" />
        </div>
        <a asp-action="Index" asp-controller="TimeSpan" class="btn btn-default btn-block" role="button">Назад</a>
    </form>
</div>

SiteMonitoring/Views/TimeSpan/Details.cshtml
@model SiteMonitoring.Models.TimeSpan
@{
    ViewBag.Title = "Подробная информация";
}

<ol class="breadcrumb">
    <li><a asp-action="Index" asp-controller="Home">Главная</a></li>
    <li><a asp-action="Index" asp-controller="TimeSpan">Промежуток времени</a></li>
    <li class="active">@ViewBag.Title</li>
</ol>
<div class="container-fluid">
    <div class="panel panel-primary">
        <div class="panel-heading">@ViewBag.Title</div>
        <table class="table">
            <tbody>
                <tr>
                    <th scope="row">Название</th>
                    <td>@Model.Minutes</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="form-group">
        <a asp-action="Edit" class="btn btn-primary btn-block" asp-route-id="@Model.Id">Изменить</a>
    </div>
    <a asp-action="Index" asp-controller="TimeSpan" class="btn btn-default btn-block" role="button">Назад</a>
</div>

SiteMonitoring/Views/TimeSpan/Edit.cshtml
@model SiteMonitoring.Models.TimeSpan
@{
    ViewBag.Title = "Изменение промежутка времени";
}

<ol class="breadcrumb">
    <li><a asp-action="Index" asp-controller="Home">Главная</a></li>
    <li><a asp-action="Index" asp-controller="TimeSpan">Промежуток времени</a></li>
    <li class="active">@ViewBag.Title</li>
</ol>
<div class="container-fluid">
    <form asp-action="Edit">
        <div class="panel panel-primary">
            <div class="panel-heading">@ViewBag.Title</div>
            <div class="panel-body">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Minutes" class="control-label"></label>
                    <input asp-for="Minutes" class="form-control" />
                    <span asp-validation-for="Minutes" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Изменить" class="btn btn-primary btn-block" />
        </div>
        <a asp-action="Index" asp-controller="TimeSpan" class="btn btn-default btn-block" role="button">Назад</a>
    </form>
</div>

SiteMonitoring/Views/TimeSpan/Index.cshtml
@model IEnumerable<SiteMonitoring.Models.TimeSpan>
@{
    ViewBag.Title = "Промежуток времени";
}

<ol class="breadcrumb">
    <li><a asp-action="Index" asp-controller="Home">Главная</a></li>
    <li class="active">@ViewBag.Title</li>
</ol>

<div class="container-fluid">
    <div class="panel panel-primary">
        <div class="panel-heading">@ViewBag.Title</div>
        <table class="table">
            <tr>
                <th>Промежуток времени</th>
                <th>Действия</th>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => Model.FirstOrDefault().Minutes)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@Model.FirstOrDefault().Id"><span class="glyphicon glyphicon-pencil"></span></a> |
                    <a asp-action="Details" asp-route-id="@Model.FirstOrDefault().Id"><span class="glyphicon glyphicon-info-sign"></span></a> |
                    <a asp-action="Delete" asp-route-id="@Model.FirstOrDefault().Id"><span class="glyphicon glyphicon-trash"></span></a>
                </td>
            </tr>
        </table>
    </div>
</div>